In [3]:
import torch
import math

In [6]:
x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [7]:
zeros = torch.zeros(2, 3)
print(zeros)

ones = torch.ones(2, 3)
print(ones)

torch.manual_seed(1729)
random = torch.rand(2, 3)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [12]:
# create a tensor from a list 
tensor_a = torch.tensor([1, 2, 3, 4])
print(f"tensor A: {tensor_a}")

# create a tensor with specified shape
tensor_b = torch.zeros((2, 3))  # 2x3 tensor filled with zeros
print(f"tensor B: {tensor_b}")

# Create a tensor with random values
tensor_c = torch.rand((3, 4))  # 3x4 tensor with random values
print(f"tensor C: {tensor_c}")

tensor A: tensor([1, 2, 3, 4])
tensor B: tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor C: tensor([[0.0703, 0.5105, 0.9451, 0.2359],
        [0.1979, 0.3327, 0.6146, 0.5999],
        [0.5013, 0.9397, 0.8656, 0.5207]])


In [13]:
# check tensor shapes
print(f"shape of tensor A: {tensor_a.shape}")
print(f"shape of tensor B: {tensor_b.shape}")
print(f"shape of tensor C: {tensor_c.shape}")

shape of tensor A: torch.Size([4])
shape of tensor B: torch.Size([2, 3])
shape of tensor C: torch.Size([3, 4])


In [14]:
# reshape tensor_c to a 2x6 tensor
tensor_c_reshaped = tensor_c.view(2, 6)
print(f"reshaped tensor C: {tensor_c_reshaped}")
print(f"shape of reshaped tensor C: {tensor_c_reshaped.shape}")

reshaped tensor C: tensor([[0.0703, 0.5105, 0.9451, 0.2359, 0.1979, 0.3327],
        [0.6146, 0.5999, 0.5013, 0.9397, 0.8656, 0.5207]])
shape of reshaped tensor C: torch.Size([2, 6])


In [16]:
# element-wise addition
tensor_d = tensor_a + torch.tensor([5, 6, 7, 8])
print(f"tensor D (element-wise addition): {tensor_d}")

# matrix multiplication
tensor_e = torch.matmul(torch.tensor([[1, 2], [3, 4]]), torch.tensor([[5, 6], [7, 8]]))
print(f"tensor E (matrix multiplication): {tensor_e}")

tensor D (element-wise addition): tensor([ 6,  8, 10, 12])
tensor E (matrix multiplication): tensor([[19, 22],
        [43, 50]])


In [17]:
# broadcasting example: adding a vector to a matrix
matrix = torch.rand((3, 4))
vector = torch.tensor([1, 2, 3, 4])
result = matrix + vector  # broadcasting the vector to each row of the matrix
print(f"matrix after broadcasting: {result}")

matrix after broadcasting: tensor([[1.6865, 2.3614, 3.6493, 4.2633],
        [1.4762, 2.0548, 3.2024, 4.5731],
        [1.7191, 2.4067, 3.7301, 4.6276]])


In [18]:
# create a tensor with requires_grad=True to track computations
x = torch.tensor(2.0, requires_grad=True)

# perform operations on the tensor
y = x ** 2 + 3 * x + 1

# compute gradients (backward pass)
y.backward()

# print the gradient
print(f"Gradient of y with respect to x: {x.grad}")

Gradient of y with respect to x: 7.0


In [19]:
import torch.nn as nn
import torch.optim as optim

# define a simple neural network
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(1, 10)
        self.fc2 = nn.Linear(10, 1)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x

# create the network and define the loss function and optimizer
net = SimpleNN()
criterion = nn.MSELoss()
optimizer = optim.SGD(net.parameters(), lr=0.01)

# dummy input and target
inputs = torch.tensor([[1.0], [2.0], [3.0], [4.0]])
targets = torch.tensor([[2.0], [4.0], [6.0], [8.0]])

# training loop
for epoch in range(100):
    optimizer.zero_grad()  # zero the gradient buffers
    outputs = net(inputs)  # forward pass
    loss = criterion(outputs, targets)  # compute loss
    loss.backward()  # backward pass (compute gradients)
    optimizer.step()  # update weights

print(f"final loss: {loss.item()}")


final loss: 0.08624911308288574
